// packages/react/src/server.ts
import { createElement, type ComponentType } from "react";
import { renderToReadableStream, renderToString as toString } from "react-dom/server";
import type { Rendered, View } from "cf-lite/adapter";
import { compose } from "./compose.js";

export async function render(view: View): Promise<Rendered> {
  return { body: (await renderToReadableStream(compose(view))) as unknown as ReadableStream<Uint8Array> };
}
export async function renderToString(view: View) {
  return { body: toString(compose(view)) };
}

/** Component preview (cf-lite `/__preview`): the component with fixed props as a router-agnostic Page. */
export const bind = (Component: unknown, props: Record<string, unknown>) => () => createElement(Component as ComponentType<any>, props);

// packages/solid/src/server.ts
import { createComponent, type Component } from "solid-js";
import { generateHydrationScript, renderToStream, renderToString as toString } from "solid-js/web";
import type { Rendered, View } from "cf-lite/adapter";
import { compose } from "./compose.js";

/** Streaming SSR (`renderToStream`; Suspense boundaries resolve in order on the same stream). Hydration bootstrap goes into <head> only when the page hydrates. */
export async function render(view: View): Promise<Rendered> {
  const { readable, writable } = new TransformStream<Uint8Array, Uint8Array>();
  renderToStream(() => compose(() => view)).pipeTo(writable as never);
  return { body: readable, head: view.hydrate ? generateHydrationScript() : undefined };
}
export async function renderToString(view: View) {
  return { body: toString(() => compose(() => view)), head: view.hydrate ? generateHydrationScript() : undefined };
}

/** Component preview (cf-lite `/__preview`): the component with fixed props as a router-agnostic Page. */
export const bind = (C: unknown, props: Record<string, unknown>) => () => createComponent(C as Component<any>, props);
